LIBNAME HRS 'L:\HRS\DATA' ;
RUN;


*SCWGT INVERSEWEIGHT;

ODS PDF FILE = "L:\HRS\HRSPAINOUTPUT03062021.PDF";
*PAIN PRESENCE;
TITLE "PREDICTING PAIN PRESENCE";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF="1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL PERSIST_PAINSTATUS = AGEC CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=NORM;
 REPEATED SUBJECT=HHIDPN  /CORR=EXCH;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1;
 ESTIMATE "RAGENDER" RAGENDER 1 -1;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1;
 ESTIMATE "CESD" CESD 1;
 ESTIMATE "CONDE" CONDE 1;
 ESTIMATE "SMOKING" SMOKEN 1;
 ESTIMATE "DRINKING" DRINK 1;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1;
 RUN;



*PAIN INTENSITY;
TITLE "PREDICTING PAIN INTENSITY";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF="1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL PERSIST_PAININTEN (REF="0") = AGEC CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=NORM;
 REPEATED SUBJECT=HHIDPN  /CORR=INDEP;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1;
 ESTIMATE "RAGENDER" RAGENDER 1 -1;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1;
 ESTIMATE "CESD" CESD 1;
 ESTIMATE "CONDE" CONDE 1;
 ESTIMATE "SMOKING" SMOKEN 1;
 ESTIMATE "DRINKING" DRINK 1;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1;
 RUN;



*PAIN INTERFERENCE;
TITLE "PREDICTING PAIN INTERFERENCE";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF="1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL PERSIST_PAININTERFER(REF="0") = AGEC CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=NORM;
 REPEATED SUBJECT=HHIDPN  /CORR=EXCH;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1;
 ESTIMATE "RAGENDER" RAGENDER 1 -1;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1;
 ESTIMATE "CESD" CESD 1;
 ESTIMATE "CONDE" CONDE 1;
 ESTIMATE "SMOKING" SMOKEN 1;
 ESTIMATE "DRINKING" DRINK 1;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1;
 RUN;


 DATA WORK.HRSTEMP;
SET HRS.HRSLONG03042021;
SCI_LAG = LAG(SCI);
IF INDEX1 =1 THEN SCI_LAG = .;
SCINEW = SCI - SCI_LAG;
RUN;


*PAIN PAINSTATUSPERCENT ;
TITLE "PERSISTENT PAIN STATUS PREDICTING SCI";
PROC GENMOD DATA=WORK.HRSTEMP DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE . AND SCINEW IN(0,1);
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF="1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL SCINEW (REF="0")= AGEC PERSIST_PAINSTATUS CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=BINOMIAL LINK=LOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=AR(1);
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAINSTATUS ~ 1" PERSIST_PAINSTATUS 1/EXP;
 ESTIMATE "PERSIST_PAINSTATUS ~ 2" PERSIST_PAINSTATUS 2/EXP;
 ESTIMATE "PERSIST_PAINSTATUS ~ 3" PERSIST_PAINSTATUS 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;




************************************************
SCD MODELS
************************************************;


*PAIN PAINSTATUSPERCENT ;
TITLE "PERSISTENT PAIN STATUS PREDICTING SCI";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF="1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL SCI(REF="0")= AGEC PERSIST_PAINSTATUS CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=BINOMIAL LINK=LOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=AR(1);
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAINSTATUS ~ 1" PERSIST_PAINSTATUS 1/EXP;
 ESTIMATE "PERSIST_PAINSTATUS ~ 2" PERSIST_PAINSTATUS 2/EXP;
 ESTIMATE "PERSIST_PAINSTATUS ~ 3" PERSIST_PAINSTATUS 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;


*PAIN INTENSITY;
TITLE "PERSISTENT PAIN INTENSITY PREDICTING SCI";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF="1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL SCI(REF="0")= AGEC PERSIST_PAININTEN CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=BINOMIAL LINK=LOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=AR(1);
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAININTEN ~ 1" PERSIST_PAININTEN 1/EXP;
 ESTIMATE "PERSIST_PAININTEN ~ 2" PERSIST_PAININTEN 2/EXP;
 ESTIMATE "PERSIST_PAININTEN ~ 3" PERSIST_PAININTEN 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;

*PAIN INTERFERENCE;
TITLE "PERSISTENT PAIN INTERFERENCE PREDICTING SCI";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF="1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL SCI(REF="0")= AGEC PERSIST_PAININTERFER CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=BINOMIAL LINK=LOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=AR(1);
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAININTERFER ~ 1" PERSIST_PAININTERFER 1/EXP;
 ESTIMATE "PERSIST_PAININTERFER ~ 2" PERSIST_PAININTERFER 2/EXP;
 ESTIMATE "PERSIST_PAININTERFER ~ 3" PERSIST_PAININTERFER 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;

************************************************
COGNITIVE DECLINE MODELS
************************************************;


*PAIN INTERFERENCE;
TITLE "PERSISTENT PAIN PRESENCE PREDICTING COGTOT";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
  WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL COGTOT = AGEC PERSIST_PAINSTATUS CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=NORML;
 REPEATED SUBJECT=HHIDPN  /CORR=EXCH;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PAINSTATUSPERCENT ~ 1" PERSIST_PAINSTATUS 1;
 ESTIMATE "PAINSTATUSPERCENT ~ 2" PERSIST_PAINSTATUS 2;
 ESTIMATE "PAINSTATUSPERCENT ~ 3" PERSIST_PAINSTATUS 3;
 ESTIMATE "RAGENDER" RAGENDER 1 -1;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1 ;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1;
 ESTIMATE "CESD" CESD 1;
 ESTIMATE "CONDE" CONDE 1;
 ESTIMATE "SMOKING" SMOKEN 1;
 ESTIMATE "DRINKING" DRINK 1;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1;
 RUN;



*PAIN INTENSITY;
TITLE "PERSISTENT PAIN INTENSITY PREDICTING COGTOT";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL COGTOT = AGEC PERSIST_PAININTEN CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=NORML;
 SCWGT INVERSEWEIGHT;
 REPEATED SUBJECT=HHIDPN /CORR=EXCH;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAININTEN ~ 1" PERSIST_PAININTEN 1;
 ESTIMATE "PERSIST_PAININTEN ~ 2" PERSIST_PAININTEN 2;
 ESTIMATE "PERSIST_PAININTEN ~ 3" PERSIST_PAININTEN 3;
 ESTIMATE "RAGENDER" RAGENDER 1 -1;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1 ;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1;
 ESTIMATE "CESD" CESD 1;
 ESTIMATE "CONDE" CONDE 1;
 ESTIMATE "SMOKING" SMOKEN 1;
 ESTIMATE "DRINKING" DRINK 1;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1;
RUN;



*PAIN INTERFERENCE;
TITLE "PERSISTENT PAIN INTERFERENCE PREDICTING COGTOT";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL COGTOT = AGEC PERSIST_PAININTERFER CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=NORML;
 REPEATED SUBJECT=HHIDPN  /CORR=EXCH;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1 ;
 ESTIMATE "PERSIST_PAININTERFER ~ 1 " PERSIST_PAININTERFER 1;
 ESTIMATE "PERSIST_PAININTERFER ~ 2" PERSIST_PAININTERFER 2;
 ESTIMATE "PERSIST_PAININTERFER ~ 3" PERSIST_PAININTERFER 5;
 ESTIMATE "RAGENDER" RAGENDER 1 -1;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1 ;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1;
 ESTIMATE "CESD" CESD 1;
 ESTIMATE "CONDE" CONDE 1;
 ESTIMATE "SMOKING" SMOKEN 1;
 ESTIMATE "DRINKING" DRINK 1;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1;
 RUN;





*PREDICTING CI <1.5;

*PAIN PRESENCE;
TITLE "PERSISTENT PAIN PRESENCE PREDICTING CI <1.5";
 PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL CI= AGEC PERSIST_PAINSTATUS CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL / DIST=BINOMIAL LINK=LOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=INDEP;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAINSTATUS ~ 1" PERSIST_PAINSTATUS 1/EXP;
 ESTIMATE "PERSIST_PAINSTATUS ~ 2" PERSIST_PAINSTATUS 2/EXP;
 ESTIMATE "PERSIST_PAINSTATUS ~ 3" PERSIST_PAINSTATUS 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1 /EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;



*PAIN SEVERITY;
TITLE "PERSISTENT PAIN SEVERITY PREDICTING CI <1.5";
 PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL CI= AGEC PERSIST_PAININTEN CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL / DIST=BINOMIAL LINK=LOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=INDEP;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAININTEN ~ 1" PERSIST_PAININTEN 1/EXP;
 ESTIMATE "PERSIST_PAININTEN ~ 2" PERSIST_PAININTEN 2/EXP;
 ESTIMATE "PERSIST_PAININTEN ~ 3" PERSIST_PAININTEN 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1 /EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;



*PAIN INTERFERENCE;
TITLE "PERSISTENT PAIN INTERFERENCE PREDICTING CI <1.5";
 PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL CI= AGEC PERSIST_PAININTERFER CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL / DIST=BINOMIAL LINK=LOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=INDEP;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAININTERFER 1" PERSIST_PAININTERFER 1/EXP;
 ESTIMATE "PERSIST_PAININTERFER 2" PERSIST_PAININTERFER 2/EXP;
 ESTIMATE "PERSIST_PAININTERFER 3" PERSIST_PAININTERFER 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1 /EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;

*MULTINOMIAL MODELS;

*PAIN PRESENCE;
TITLE "PERSISTENT PAIN PRESENCE PREDICTING CI <1.5";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGEC>=0 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL CIORD = AGEC PERSIST_PAINSTATUS CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL / DIST=MULTINOMIAL LINK=CUMLOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=INDEP;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAINSTATUS 1" PERSIST_PAINSTATUS 1/EXP;
 ESTIMATE "PERSIST_PAINSTATUS 2" PERSIST_PAINSTATUS 2/EXP;
 ESTIMATE "PERSIST_PAINSTATUS 3" PERSIST_PAINSTATUS 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;

*PAIN INTENSITY;
TITLE "PERSISTENT PAIN INTENSITY PREDICTING CI <1.5";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL CIORD(REF="0")= AGEC PERSIST_PAININTEN CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL/ DIST=MULTINOMIAL LINK=CUMLOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=INDEP;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAININTEN 1" PERSIST_PAININTEN 1/EXP;
 ESTIMATE "PERSIST_PAININTEN 2" PERSIST_PAININTEN 2/EXP;
 ESTIMATE "PERSIST_PAININTEN 3" PERSIST_PAININTEN 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1 /EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;


*PAIN INTERFERENCE;
TITLE "PERSISENT PAIN INTERFERENCE PREDICTING CI <1.5";
PROC GENMOD DATA=HRS.HRSLONG03042021 DESCENDING;
 WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .;
 CLASS HHIDPN  RAGENDER(REF="1") HACOHORT RARACEM(REF = "1") INCOME_BCAT(REF="2") EDUC_BCAT(REF="2");
 MODEL CIORD= AGEC PERSIST_PAININTERFER CONDE CESD RAGENDER INCOME_BCAT EDUC_BCAT RARACEM SMOKEN DRINK NVALIDTOTAL / DIST=MULTINOMIAL LINK=CUMLOGIT;
 REPEATED SUBJECT=HHIDPN  /CORR=INDEP;
 SCWGT INVERSEWEIGHT;
 ESTIMATE "AGE" AGEC 1/EXP ;
 ESTIMATE "PERSIST_PAININTERFER ~ 1"  PERSIST_PAININTERFER 1/EXP;
 ESTIMATE "PERSIST_PAININTERFER ~ 2"  PERSIST_PAININTERFER 2/EXP;
 ESTIMATE "PERSIST_PAININTERFER ~ 3"  PERSIST_PAININTERFER 3/EXP;
 ESTIMATE "RAGENDER" RAGENDER 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS OTHER" RARACEM 0 1 -1/EXP;
 ESTIMATE "RACE WHITE VERSUS BLACK" RARACEM 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS <HS" EDUC_BCAT 1 0 -1/EXP;
 ESTIMATE "EDUC_BCATHS VERSUS > HS" EDUC_BCAT 0 1 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO LESS THAN 30K" INCOME_BCAT 1 0 0 -1 /EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO 30K TO 60K" INCOME_BCAT 0 1 0 -1/EXP;
 ESTIMATE "INCOME_BCAT 16 TO 30K TO >60K" INCOME_BCAT 0 0 1 -1/EXP;
 ESTIMATE "CESD" CESD 1/EXP;
 ESTIMATE "CONDE" CONDE 1/EXP;
 ESTIMATE "SMOKING" SMOKEN 1/EXP;
 ESTIMATE "DRINKING" DRINK 1/EXP;
 ESTIMATE "NVALIDTOTAL" NVALIDTOTAL 1/EXP;
 RUN;

ODS PDF CLOSE;

*TABLE 1;

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=1;
TABLE PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER CI CIORD SCI RAGENDER INCOME_BCAT EDUC_BCAT RARACEM CONDE SMOKEN DRINK;
RUN;

 TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=1;
VAR AGE_B COGTOT CONDE CESD;
RUN;

DATA HRS.HRSLONG03042021TEMP;
SET HRS.HRSLONG03042021;
PERSISTPAINPRESENCECAT = .;
IF PERSIST_PAINSTATUS = 0 THEN PERSISTPAINPRESENCECAT = 0;
IF PERSIST_PAINSTATUS = 1 THEN PERSISTPAINPRESENCECAT = 1;
IF PERSIST_PAINSTATUS = 2 THEN PERSISTPAINPRESENCECAT = 2;
IF PERSIST_PAINSTATUS >3 THEN PERSISTPAINPRESENCECAT = 3;

PERSISTPAININTENCAT = .;
IF 0 < PERSIST_PAININTEN <.99 THEN PERSISTPAININTENCAT = 0;
IF 1 < PERSIST_PAININTEN <1.99 THEN PERSISTPAININTENCAT = 1;
IF 2 < PERSIST_PAININTEN <2.99 THEN PERSISTPAININTENCAT = 2;
IF  PERSIST_PAININTENS >3 THEN PERSISTPAININTENCAT = 3;

PERSISTPAININTERFERCAT = .;
IF PERSIST_PAININTERFER = 0 THEN PERSISTPAININTERFERCAT = 0;
IF PERSIST_PAININTERFER = 1 THEN PERSISTPAININTERFERCAT = 1;
IF PERSIST_PAININTERFER = 2 THEN PERSISTPAININTERFERCAT = 2;
IF PERSIST_PAININTERFER >3 THEN PERSISTPAININTERFERCAT = 3;
RUN;

*SUPPLEMENTARY TABLE 1;

*WAVE 1 (HRS WAVE 4);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=1;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

 TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=1;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;

*WAVE 2 (HRS WAVE 5);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=2;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=2;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;


*WAVE 3 (HRS WAVE 6);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=3;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=3;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;


*WAVE 4 (HRS WAVE 7);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=4;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=4;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;



*WAVE 5 (HRS WAVE 8);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=5;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=5;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;




*WAVE 6 (HRS WAVE 9);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=6;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=6;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;




*WAVE 7 (HRS WAVE 10);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=7;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=7;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;


*WAVE 8 (HRS WAVE 11);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=8;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=8;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;


*WAVE 9 (HRS WAVE 12);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=9;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=9;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;



*WAVE 10 (HRS WAVE 13);

TITLE "BASELINE FREQUENCIES";
PROC FREQ DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=10;
TABLE PAINSTATUS PAININTENSITYC PAININTERFERC CI CIORD SCI RAGENDER RARACEM SMOKEN DRINK;
RUN;

TITLE "BASELINE MEAN AND SD";
PROC MEANS DATA=HRS.HRSLONG03042021;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=10;
VAR PERSIST_PAINSTATUS PERSIST_PAININTEN PERSIST_PAININTERFER RAGEY COGTOT CONDE CESD;
RUN;

DATA HRS.HRSLONG03042021TEMP;
SET HRS.HRSLONG03042021;
RUN;


PROC SORT DATA =  HRS.HRSLONG03042021TEMP;
BY HHIDPN INDEX1;
RUN;


 data HRS.HRSLONG03042021TEMP;
 SET HRS.HRSLONG03042021;
 by  HHIDPN;
   IF LAST.HHIDPN THEN LAST = 1;
run;



*EXCLUSION TREE;


 TITLE "BASELINE FREQUENCIES";
PROC MEANS DATA=HRS.HRSLONG03042021TEMP N;
WHERE INDEX1=1;
VAR PAINSTATUS COGTOT;
RUN;
*n = 21362;

 TITLE "BASELINE FREQUENCIES";
PROC MEANS DATA=HRS.HRSLONG03042021TEMP N;
WHERE INDEX1=1 AND PROXY = 0;
VAR PAINSTATUS COGTOT;
RUN;
*n = 19339;

TITLE "BASELINE FREQUENCIES";
PROC MEANS DATA=HRS.HRSLONG03042021TEMP N;
WHERE INDEX1=1 AND PROXY = 0 AND AGE_B GE 65;
VAR PAINSTATUS COGTOT;
RUN;
*n = 9513;

TITLE "BASELINE FREQUENCIES";
PROC MEANS DATA=HRS.HRSLONG03042021TEMP N;
WHERE INDEX1=1 AND PROXY = 0 AND AGE_B GE 65 AND COGTOT NE .;
VAR PAINSTATUS COGTOT;
RUN;
*n = 9513;

TITLE "BASELINE FREQUENCIES";
PROC MEANS DATA=HRS.HRSLONG03042021TEMP N;
WHERE INDEX1=1 AND PROXY = 0 AND AGE_B GE 65 AND COGTOT NE . AND MEMDIS = 0 AND  STROKE = 0;
VAR PAINSTATUS COGTOT;
RUN;
*n = 9513;

 TITLE "BASELINE FREQUENCIES";
PROC MEANS DATA=HRS.HRSLONG03042021TEMP N;
WHERE PROXY = 0 ;
AND INDEX1=1;
VAR PAINSTATUS COGTOT;
RUN;


 TITLE "BASELINE FREQUENCIES";
PROC MEANS DATA=HRS.HRSLONG03042021TEMP N;
WHERE PROXY = 0 AND AGE_B >=65 AND STROKE NE 1 AND MEMDIS = 0 AND ELIGW4=1 AND PAINSTATUSW4 NE . AND R4COGTOT NE .
AND INDEX1=1;
VAR PAINSTATUS COGTOT;
RUN;
